### ISSUE TITLE
Package install failure 

### ISSUE THREAD

**Issue by finessin87** [ColdGrub1384/LibTerm-Packages#14]
Package installer fails to successfully install the available packages. I am connected to WiFi with a good ping. I have both LibTerm and OpenTerm installed on my iPhone X 256G on iOS 11.4.1 (tvOS 11 Beta Profile is installed)

**Comment by ColdGrub1384** [comment]
Thank you for reporting the bug. Does it fails for all packages?

**Comment by finessin87** [comment]
I’m not sure if you have already made some changes in the code or not but I just launched the app again and it is working fine for me now. I appreciate your work and I love the app and UI. Awesome work man!

**Comment by ColdGrub1384** [comment]
Thank you! I don't changed anything. Maybe it's a problem on caches.
