### ISSUE TITLE
Is There Any Method to test one zip package . 

### ISSUE THREAD

**Issue by v1xingyue** [ColdGrub1384/LibTerm-Packages#19]
I want to write some python3 code implements one function. But How can I debug my package to make sure no bug with my package .

**Comment by Shock9616** [comment]
I use Pythonista on my iPad to make sure that the code works. It’s a paid app but it is totally worth it since you get a complete python IDE on your device.

**Comment by Minion3665** [comment]
I use python3 IDE Fresh Edition on my ipad. It has a confusing interface, and does not have all the features of Pythonista but it's free.

**Comment by Shock9616** [comment]
You could also load the python script inside the app and run it with the python or python3 command... that would be good since then you would be testing it in the environment that it will be running in.

**Comment by v1xingyue** [comment]
> You could also load the python script inside the app and run it with the python or python3 command... that would be good since then you would be testing it in the environment that it will be running in.

The Problem is that I can't even compile it , But across problems.   
[https://github.com/ColdGrub1384/LibTerm/issues/25(https://github.com/ColdGrub1384/LibTerm/issues/25)
Would you please help me ?

**Comment by Shock9616** [comment]
What do you mean you can’t compile it? All you would need to do is copy it to the LibTerm folder in the files app, cd to the directory that it’s in, then type python _myscript_.py. You can’t actually use the python3 command in this app. Use the python command and it will use python 3 if you have purchased the python 3 feature. Here is a video showing what I mean. https://www.dropbox.com/s/0i05xqr47rrcudq/RPReplay_Final1560089939.MP4?dl=0

**Comment by ColdGrub1384** [comment]
Sorry for the late response. Just run the script. Then, you need to create a zip file with the script and any other dependency. Make sure to zip the scripts directly and not a directory.

**Comment by ColdGrub1384** [comment]
The scripts are placed in `~/Library/scripts`. So, you can place them there and the scripts will be available as commands.

**Comment by v1xingyue** [comment]
> What do you mean you can’t compile it? All you would need to do is copy it to the LibTerm folder in the files app, cd to the directory that it’s in, then type python _myscript_.py. You can’t actually use the python3 command in this app. Use the python command and it will use python 3 if you have purchased the python 3 feature. Here is a video showing what I mean. https://www.dropbox.com/s/0i05xqr47rrcudq/RPReplay_Final1560089939.MP4?dl=0

That's great thank you very much . I got the way . ^_^
