### ISSUE TITLE
Feature Request: Make a Pip module

### ISSUE THREAD

**Issue by VincentCCandela** [ColdGrub1384/LibTerm-Packages#23]
It would be nice if there could be a pip module to install python modules.

**Comment by ColdGrub1384** [comment]
Python modules can be installed like this `python -m pip install <>`

**Comment by ColdGrub1384** [comment]
Only Pure Python modules can be installed.

**Comment by rhyxoduzz** [comment]
So we cant download pip 3 on Libterm?

**Comment by dullbananas** [comment]
It already exists, but it's not the official complete Pip implementation

**Comment by rhyxoduzz** [comment]
![B5E15550-1085-498B-A809-08FF2BB701F6](https://user-images.githubusercontent.com/57494386/69523817-c2c30980-0f9f-11ea-8504-e489cd81e160.png)

**Comment by spinto111** [comment]
Did you find a solution @rhyxoduzz? Having the same issue trying to install Speedtest pip module

**Comment by Nokiand** [comment]
Going to try to install PPCI (Pure Python Compiler Infrastructure) from gitHub, if it will not go this seems something to make it so!  Hoping to compile "Language frontends for C, Python, Pascal, Basic and Brainfuck", maybe Ocaml; with LLVM and more.
