### ISSUE TITLE
Python command doesn’t work

### ISSUE THREAD

**Issue by Shock9616** [ColdGrub1384/LibTerm-Packages#8]
Since the new update for python 3, when I try to run a python file in the command line or open the python shell with the “python” command, I get an error saying that the command is not found. I have also tried typing “python3” since libterm now runs python 3 but that also doesn’t work.

**Comment by ColdGrub1384** [comment]
I'm so sorry, that's a bug. I fixed it and I submitted a new update, it will be probably available today or tomorrow.

**Comment by ColdGrub1384** [comment]
https://github.com/ColdGrub1384/LibTerm/issues/11

**Comment by Shock9616** [comment]
Ok thank you!

**Comment by ColdGrub1384** [comment]
The app is now In Review, so the update should be available in some hours.

**Comment by Shock9616** [comment]
Ok thank you!

Kaleb R.

**Comment by ColdGrub1384** [comment]
Fixed
